---
stages:
  - lint  
  - chefspec
  - default
  - copr
  - config
  - config-copr
  - deploy
  - cleanup
  - cleanup_manual

.kitchen_docker_template: &kitchen_docker_definition
  before_script:
    - echo 'We are using docker.'
    - export KITCHEN_YAML=.kitchen.yml
    - export KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
    - pwd
    - chef --version
    - kitchen --version

.chef_docker_template: &chef_docker_template
  image: registry.gitlab.bmhughes.co.uk/bmhughes-net-docker/chefdk:latest

foodcritic:
  stage: lint
  <<: *chef_docker_template
  script:
    - chef --version
    - cookstyle --version
    - foodcritic --version
    - foodcritic .
  tags:
    - chef
  except:
    variables:
      - $MANUAL_CLEANUP

cookstyle:
  stage: lint
  <<: *chef_docker_template
  script:
    - chef --version
    - cookstyle --version
    - foodcritic --version
    - cookstyle .
  tags:
    - chef
  except:
    variables:
      - $MANUAL_CLEANUP

chefspec:
  stage: chefspec
  <<: *chef_docker_template
  script:
    - chef --version
    - cookstyle --version
    - foodcritic --version
    - mkdir -p artifacts
    - chef exec bundle install
    - chef exec rspec
    - mv -f coverage artifacts/
  except:
    variables:
      - $MANUAL_CLEANUP
  tags:
    - chef
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHA"
    when: always
    expire_in: 3 days
    paths:
      - artifacts/

.kitchen_suite_definition_default-centos-7: &kitchen_suite_definition_default-centos-7
  stage: default
  variables:
    KITCHEN_NAME: default-centos-7

.kitchen_suite_definition_default-fedora-latest: &kitchen_suite_definition_default-fedora-latest
  stage: default
  variables:
    KITCHEN_NAME: default-fedora-latest

.kitchen_suite_definition_default-ubuntu-1604: &kitchen_suite_definition_default-ubuntu-1604
  stage: default
  variables:
    KITCHEN_NAME: default-ubuntu-1604

.kitchen_suite_definition_default-ubuntu-1804: &kitchen_suite_definition_default-ubuntu-1804
  stage: default
  variables:
    KITCHEN_NAME: default-ubuntu-1804

.kitchen_suite_definition_default-debian-8: &kitchen_suite_definition_default-debian-8
  stage: default
  variables:
    KITCHEN_NAME: default-debian-8

.kitchen_suite_definition_default-debian-9: &kitchen_suite_definition_default-debian-9
  stage: default
  variables:
    KITCHEN_NAME: default-debian-9

.kitchen_suite_definition_default-amazonlinux-2: &kitchen_suite_definition_default-amazonlinux-2
  stage: default
  variables:
    KITCHEN_NAME: default-amazonlinux-2

.kitchen_suite_definition_copr-centos-7: &kitchen_suite_definition_copr-centos-7
  stage: copr
  variables:
    KITCHEN_NAME: copr-centos-7

.kitchen_suite_definition_copr-fedora-latest: &kitchen_suite_definition_copr-fedora-latest
  stage: copr
  variables:
    KITCHEN_NAME: copr-fedora-latest

.kitchen_suite_definition_config-centos-7: &kitchen_suite_definition_config-centos-7
  stage: config
  variables:
    KITCHEN_NAME: config-centos-7

.kitchen_suite_definition_config-fedora-latest: &kitchen_suite_definition_config-fedora-latest
  stage: config
  variables:
    KITCHEN_NAME: config-fedora-latest

.kitchen_suite_definition_config-ubuntu-1604: &kitchen_suite_definition_config-ubuntu-1604
  stage: config
  variables:
    KITCHEN_NAME: config-ubuntu-1604

.kitchen_suite_definition_config-ubuntu-1804: &kitchen_suite_definition_config-ubuntu-1804
  stage: config
  variables:
    KITCHEN_NAME: config-ubuntu-1804

.kitchen_suite_definition_config-debian-8: &kitchen_suite_definition_config-debian-8
  stage: config
  variables:
    KITCHEN_NAME: config-debian-8

.kitchen_suite_definition_config-debian-9: &kitchen_suite_definition_config-debian-9
  stage: config
  variables:
    KITCHEN_NAME: config-debian-9

.kitchen_suite_definition_config-amazonlinux-2: &kitchen_suite_definition_config-amazonlinux-2
  stage: config
  variables:
    KITCHEN_NAME: config-amazonlinux-2

.kitchen_suite_definition_config-copr-centos-7: &kitchen_suite_definition_config-copr-centos-7
  stage: config-copr
  variables:
    KITCHEN_NAME: config-copr-centos-7

.kitchen_suite_definition_config-copr-fedora-latest: &kitchen_suite_definition_config-copr-fedora-latest
  stage: config-copr
  variables:
    KITCHEN_NAME: config-copr-fedora-latest

.kitchen_test_definition: &kitchen_test_definition
  script:
    - kitchen converge $KITCHEN_NAME
    - kitchen verify $KITCHEN_NAME
    - rm -rf etc
    - mkdir -p etc
    - kitchen exec $KITCHEN_NAME -c "rsync -a --no-links /etc/syslog-ng /var/gitlab-runner-artifacts/${CI_JOB_NAME}-${CI_COMMIT_SHA}/"
    - cp -Rfvp /tmp/gitlab-runner-artifacts/$CI_JOB_NAME-$CI_COMMIT_SHA/* etc/
    - kitchen destroy $KITCHEN_NAME
  retry: 1
  except:
    variables:
      - $MANUAL_CLEANUP
  tags:
    - chef-kitchen
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    when: always
    expire_in: 3 days
    paths:
      - etc/*
      - .kitchen/

kitchen_default-centos-7:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-centos-7

kitchen_default-fedora-latest:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-fedora-latest

kitchen_default-ubuntu-1604:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-ubuntu-1604

kitchen_default-ubuntu-1804:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-ubuntu-1804
    
kitchen_default-debian-8:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-debian-8

kitchen_default-debian-9:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-debian-9

kitchen_default-amazonlinux-2:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-amazonlinux-2

kitchen_copr-centos-7:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_copr-centos-7

kitchen_copr-fedora-latest:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_copr-fedora-latest

kitchen_config-centos-7:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-centos-7

kitchen_config-fedora-latest:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-fedora-latest

kitchen_config-ubuntu-1604:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-ubuntu-1604

kitchen_config-ubuntu-1804:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-ubuntu-1804

kitchen_config-debian-8:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-debian-8

kitchen_config-debian-9:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-debian-9

kitchen_config-amazonlinux-2:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-amazonlinux-2

kitchen_config-copr-centos-7:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-copr-centos-7

kitchen_config-copr-fedora-latest:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-copr-fedora-latest

---
stages:
  - lint  
  - chefspec
  - default
  - general_proxy
  - cleanup_test
  - streams_proxy
  - deploy
  - cleanup
  - cleanup_manual

.kitchen_docker_template: &kitchen_docker_definition
  before_script:
    - echo 'We are using docker.'
    - export KITCHEN_YAML=.kitchen.yml
    - export KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
    - pwd
    - chef --version
    - kitchen --version

.chef_docker_template: &chef_docker_template
  image: registry.gitlab.bmhughes.co.uk/bmhughes-net-docker/chefdk:latest

foodcritic:
  stage: lint
  <<: *chef_docker_template
  script:
    - chef --version
    - cookstyle --version
    - foodcritic --version
    - foodcritic .
  tags:
    - chef
  except:
    variables:
      - $MANUAL_CLEANUP

cookstyle:
  stage: lint
  <<: *chef_docker_template
  script:
    - chef --version
    - cookstyle --version
    - foodcritic --version
    - cookstyle .
  tags:
    - chef
  except:
    variables:
      - $MANUAL_CLEANUP

chefspec:
  stage: chefspec
  <<: *chef_docker_template
  script:
    - chef --version
    - cookstyle --version
    - foodcritic --version
    - mkdir -p artifacts
    - chef exec bundle install
    - chef exec rspec
    - mv -f coverage artifacts/
  except:
    variables:
      - $MANUAL_CLEANUP
  tags:
    - chef
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHA"
    when: always
    expire_in: 3 days
    paths:
      - artifacts/

.kitchen_suite_definition_default-centos-7: &kitchen_suite_definition_default-centos-7
  stage: default
  variables:
    KITCHEN_NAME: default-centos-7

.kitchen_suite_definition_default-fedora-latest: &kitchen_suite_definition_default-fedora-latest
  stage: default
  variables:
    KITCHEN_NAME: default-fedora-latest

.kitchen_suite_definition_default-ubuntu-1604: &kitchen_suite_definition_default-ubuntu-1604
  stage: default
  variables:
    KITCHEN_NAME: default-ubuntu-1604

.kitchen_suite_definition_default-ubuntu-1804: &kitchen_suite_definition_default-ubuntu-1804
  stage: default
  variables:
    KITCHEN_NAME: default-ubuntu-1804

.kitchen_suite_definition_default-debian-8: &kitchen_suite_definition_default-debian-8
  stage: default
  variables:
    KITCHEN_NAME: default-debian-8

.kitchen_suite_definition_default-debian-9: &kitchen_suite_definition_default-debian-9
  stage: default
  variables:
    KITCHEN_NAME: default-debian-9

.kitchen_suite_definition_default-amazonlinux-2: &kitchen_suite_definition_default-amazonlinux-2
  stage: default
  variables:
    KITCHEN_NAME: default-amazonlinux-2

.kitchen_suite_definition_copr-centos-7: &kitchen_suite_definition_copr-centos-7
  stage: copr
  variables:
    KITCHEN_NAME: copr-centos-7

.kitchen_suite_definition_copr-fedora-latest: &kitchen_suite_definition_copr-fedora-latest
  stage: copr
  variables:
    KITCHEN_NAME: copr-fedora-latest

.kitchen_suite_definition_config-centos-7: &kitchen_suite_definition_config-centos-7
  stage: config
  variables:
    KITCHEN_NAME: config-centos-7

.kitchen_suite_definition_config-fedora-latest: &kitchen_suite_definition_config-fedora-latest
  stage: config
  variables:
    KITCHEN_NAME: config-fedora-latest

.kitchen_suite_definition_config-ubuntu-1604: &kitchen_suite_definition_config-ubuntu-1604
  stage: config
  variables:
    KITCHEN_NAME: config-ubuntu-1604

.kitchen_suite_definition_config-ubuntu-1804: &kitchen_suite_definition_config-ubuntu-1804
  stage: config
  variables:
    KITCHEN_NAME: config-ubuntu-1804

.kitchen_suite_definition_config-debian-8: &kitchen_suite_definition_config-debian-8
  stage: config
  variables:
    KITCHEN_NAME: config-debian-8

.kitchen_suite_definition_config-debian-9: &kitchen_suite_definition_config-debian-9
  stage: config
  variables:
    KITCHEN_NAME: config-debian-9

.kitchen_suite_definition_config-amazonlinux-2: &kitchen_suite_definition_config-amazonlinux-2
  stage: config
  variables:
    KITCHEN_NAME: config-amazonlinux-2

.kitchen_suite_definition_config-copr-centos-7: &kitchen_suite_definition_config-copr-centos-7
  stage: config-copr
  variables:
    KITCHEN_NAME: config-copr-centos-7

.kitchen_suite_definition_config-copr-fedora-latest: &kitchen_suite_definition_config-copr-fedora-latest
  stage: config-copr
  variables:
    KITCHEN_NAME: config-copr-fedora-latest

.kitchen_test_definition: &kitchen_test_definition
  <<: *kitchen_tags_definition
  script:
    - kitchen converge $KITCHEN_NAME
    - kitchen verify $KITCHEN_NAME
    - kitchen exec $KITCHEN_NAME -c "rsync -a --no-links /etc/syslog-ng /var/gitlab-runner-artifacts/${CI_JOB_NAME}-${CI_COMMIT_SHA}/"
    - rm -rf etc
    - mkdir -p etc
    - cp -Rfvp /tmp/gitlab-runner-artifacts/$CI_JOB_NAME-$CI_COMMIT_SHA/* etc/
    - kitchen destroy $KITCHEN_NAME
  retry: 1
  except:
    variables:
      - $MANUAL_CLEANUP
  tags:
    - chef-kitchen
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    when: always
    expire_in: 3 days
    paths:
      - etc/*
      - .kitchen/

kitchen_default-centos-7:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-centos-7

kitchen_default-fedora-latest:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-fedora-latest

kitchen_default-ubuntu-1604:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-ubuntu-1604

kitchen_default-ubuntu-1804:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-ubuntu-1804
    
kitchen_default-debian-8:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-debian-8

kitchen_default-debian-9:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-debian-9

kitchen_default-amazonlinux-2:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-amazonlinux-2

kitchen_copr-centos-7:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_copr-centos-7

kitchen_copr-fedora-latest:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_copr-fedora-latest

kitchen_config-centos-7:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-centos-7

kitchen_config-fedora-latest:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-fedora-latest

kitchen_config-ubuntu-1604:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-ubuntu-1604

kitchen_config-ubuntu-1804:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-ubuntu-1804

kitchen_config-debian-8:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-debian-8

kitchen_config-debian-9:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-debian-9

kitchen_config-amazonlinux-2:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-amazonlinux-2

kitchen_config-copr-centos-7:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-copr-centos-7

kitchen_config-copr-fedora-latest:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_config-copr-fedora-latest

berks_upload:
  stage: deploy
  script:
    - berks install
    - berks update
    - berks verify
    - berks upload --no-freeze --force --except integration
  environment:
    name: production
  only:
    - production
  except:
    variables:
      - $MANUAL_CLEANUP
  tags:
    - chef
    - chef-berks-upload

cleanup_job:
  <<: *kitchen_docker_definition
  stage: cleanup
  script:
    - kitchen destroy all
    - sudo rm -Rf /tmp/gitlab-runner-artifacts/*
  when: always
  except:
    variables:
      - $MANUAL_CLEANUP
  tags:
      - chef
      - kitchen

manual_cleanup_job:
  <<: *kitchen_docker_definition
  stage: cleanup_manual
  script:
    - kitchen destroy all
    - sudo rm -Rf /tmp/gitlab-runner-artifacts/*
  allow_failure: false
  when: manual
  only:
    variables:
      - $MANUAL_CLEANUP
  tags:
      - chef
      - kitchen
...
