---
stages:
  - lint  
  - chefspec
  - converge
  - test
  - destroy
  - deploy
  - cleanup
  - cleanup_manual

.kitchen_docker_definition: &kitchen_docker_definition
  before_script:
    - echo 'We are using docker.'
    - export KITCHEN_YAML=.kitchen.yml
    - export KITCHEN_LOCAL_YAML=.kitchen.dokken.yml

.kitchen_tags_definition: &kitchen_tags_definition
  tags:
      - chef
      - kitchen

foodcritic:
  stage: lint
  script:
    - foodcritic .
  tags:
    - chef

cookstyle:
  stage: lint
  script:
    - cookstyle .
  tags:
    - chef

chefspec:
  stage: chefspec
  script:
    - mkdir -p artifacts
    - chef exec bundle install
    - chef exec rspec
    - mv -f coverage artifacts/
  except:
    variables:
      - $MANUAL_CLEANUP
  tags:
    - chef
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHA"
    when: always
    expire_in: 3 days
    paths:
      - artifacts/

.kitchen_suite_definition_default-centos-7: &kitchen_suite_definition_default-centos-7
  variables:
    KITCHEN_NAME: default-centos-7

.kitchen_suite_definition_default-fedora-latest: &kitchen_suite_definition_default-fedora-latest
  variables:
    KITCHEN_NAME: default-fedora-latest

.kitchen_suite_definition_default-ubuntu-1604: &kitchen_suite_definition_default-ubuntu-1604
  variables:
    KITCHEN_NAME: default-ubuntu-1604

.kitchen_suite_definition_default-ubuntu-1804: &kitchen_suite_definition_default-ubuntu-1804
  variables:
    KITCHEN_NAME: default-ubuntu-1804

.kitchen_suite_definition_default-debian-8: &kitchen_suite_definition_default-debian-8
  variables:
    KITCHEN_NAME: default-debian-8

.kitchen_suite_definition_default-debian-9: &kitchen_suite_definition_default-debian-9
  variables:
    KITCHEN_NAME: default-debian-9

.kitchen_suite_definition_default-amazonlinux-2: &kitchen_suite_definition_default-amazonlinux-2
  variables:
    KITCHEN_NAME: default-amazonlinux-2

.kitchen_converge_definition_default: &kitchen_converge_definition_default
  <<: *kitchen_tags_definition
  stage: converge
  script:
    - kitchen converge $KITCHEN_NAME
    - kitchen exec $KITCHEN_NAME -c "rsync -a --no-links /etc/syslog-ng /var/gitlab-runner-artifacts/${CI_JOB_NAME}-${CI_COMMIT_SHA}/"
    - mkdir etc
    - cp -Rfvp /tmp/gitlab-runner-artifacts/$CI_JOB_NAME-$CI_COMMIT_SHA/* etc/
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    when: always
    expire_in: 3 days
    paths:
      - etc/*
      - .kitchen/

.kitchen_converge_definition_disabled: &kitchen_converge_definition_disabled
  <<: *kitchen_tags_definition
  stage: converge
  script:
    - kitchen create $KITCHEN_NAME
    - kitchen exec $KITCHEN_NAME -c 'yum install rsync -y'
    - kitchen converge $KITCHEN_NAME
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    when: always
    expire_in: 3 days
    paths:
      - etc/*
      - .kitchen/

.kitchen_test_definition: &kitchen_test_definition
  <<: *kitchen_tags_definition
  stage: test
  script:
    - kitchen verify $KITCHEN_NAME

.kitchen_destroy_definition: &kitchen_destroy_definition
  <<: *kitchen_tags_definition
  stage: destroy
  script:
    - kitchen destroy $KITCHEN_NAME

kitchen_converge_default-centos-7:
  <<: *kitchen_docker_definition
  <<: *kitchen_converge_definition_default
  <<: *kitchen_suite_definition_default-centos-7
    
kitchen_test_default-centos-7:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-centos-7

kitchen_destroy_default-centos-7:
  <<: *kitchen_docker_definition
  <<: *kitchen_destroy_definition
  <<: *kitchen_suite_definition_default-centos-7

kitchen_converge_default-fedora-latest:
  <<: *kitchen_docker_definition
  <<: *kitchen_converge_definition_default
  <<: *kitchen_suite_definition_default-fedora-latest
    
kitchen_test_default-fedora-latest:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-fedora-latest

kitchen_destroy_default-fedora-latest:
  <<: *kitchen_docker_definition
  <<: *kitchen_destroy_definition
  <<: *kitchen_suite_definition_default-fedora-latest

kitchen_converge_default-ubuntu-1604:
  <<: *kitchen_docker_definition
  <<: *kitchen_converge_definition_default
  <<: *kitchen_suite_definition_default-ubuntu-1604
    
kitchen_test_default-ubuntu-1604:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-ubuntu-1604

kitchen_destroy_default-ubuntu-1604:
  <<: *kitchen_docker_definition
  <<: *kitchen_destroy_definition
  <<: *kitchen_suite_definition_default-ubuntu-1604

kitchen_converge_default-ubuntu-1804:
  <<: *kitchen_docker_definition
  <<: *kitchen_converge_definition_default
  <<: *kitchen_suite_definition_default-ubuntu-1804
    
kitchen_test_default-ubuntu-1804:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-ubuntu-1804

kitchen_destroy_default-ubuntu-1804:
  <<: *kitchen_docker_definition
  <<: *kitchen_destroy_definition
  <<: *kitchen_suite_definition_default-ubuntu-1804

kitchen_converge_default-debian-8:
  <<: *kitchen_docker_definition
  <<: *kitchen_converge_definition_default
  <<: *kitchen_suite_definition_default-debian-8
    
kitchen_test_default-debian-8:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-debian-8

kitchen_destroy_default-debian-8:
  <<: *kitchen_docker_definition
  <<: *kitchen_destroy_definition
  <<: *kitchen_suite_definition_default-debian-8

kitchen_converge_default-debian-9:
  <<: *kitchen_docker_definition
  <<: *kitchen_converge_definition_default
  <<: *kitchen_suite_definition_default-debian-9
    
kitchen_test_default-debian-9:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-debian-9

kitchen_destroy_default-debian-9:
  <<: *kitchen_docker_definition
  <<: *kitchen_destroy_definition
  <<: *kitchen_suite_definition_default-debian-9

kitchen_converge_default-amazonlinux-2:
  <<: *kitchen_docker_definition
  <<: *kitchen_converge_definition_default
  <<: *kitchen_suite_definition_default-amazonlinux-2
    
kitchen_test_default-amazonlinux-2:
  <<: *kitchen_docker_definition
  <<: *kitchen_test_definition
  <<: *kitchen_suite_definition_default-amazonlinux-2

kitchen_destroy_default-amazonlinux-2:
  <<: *kitchen_docker_definition
  <<: *kitchen_destroy_definition
  <<: *kitchen_suite_definition_default-amazonlinux-2  

# Only run berks upload on push to the 'production' branch
berks_upload:
  stage: deploy
  script:
    - berks install
    - berks update
    - berks verify
    - berks upload --no-freeze --force --except integration
  environment:
    name: production
  only:
    - production
  tags:
    - chef
    - chef-berks-upload

cleanup_job:
  <<: *kitchen_docker_definition
  stage: cleanup
  script:
    - kitchen destroy all
    - sudo rm -Rf /tmp/gitlab-runner-artifacts/*
  when: always
  tags:
      - chef
      - kitchen

manual_cleanup_job:
  <<: *kitchen_docker_definition
  stage: cleanup_manual
  script:
    - kitchen destroy all
    - sudo rm -Rf /tmp/gitlab-runner-artifacts/*
  allow_failure: false
  when: manual
  only:
    variables:
      - $MANUAL_CLEANUP
  tags:
      - chef
      - kitchen
...
