---
stages:
  - lint  
  - chefspec
  - default
  - latest
  - manual
  - githead
  - config
  - deploy
  - cleanup
  - cleanup_manual

.kitchen_docker_template: &kitchen_docker_template
  before_script:
    - echo 'We are using docker.'
    - export KITCHEN_YAML=kitchen.yml
    - export KITCHEN_LOCAL_YAML=kitchen.dokken.yml
    - whoami
    - pwd
    - chef --version
    - kitchen --version

.chef_docker_template: &chef_docker_template
  image: registry.gitlab.bmhughes.co.uk/bmhughes-net-docker/chefworkstation:latest

foodcritic:
  stage: lint
  <<: *chef_docker_template
  script:
    - chef --version
    - cookstyle --version
    - foodcritic --version
    - foodcritic .
  tags:
    - chef
  except:
    refs:
    - production
    variables:
      - $MANUAL_CLEANUP

cookstyle:
  stage: lint
  <<: *chef_docker_template
  script:
    - chef --version
    - cookstyle --version
    - foodcritic --version
    - cookstyle .
  tags:
    - chef
  except:
    refs:
    - production
    variables:
      - $MANUAL_CLEANUP

chefspec:
  stage: chefspec
  <<: *chef_docker_template
  script:
    - chef --version
    - cookstyle --version
    - foodcritic --version
    - mkdir -p artifacts
    - chef exec bundle install
    - chef exec rspec
    - mv -f coverage artifacts/
  except:
    refs:
    - production
    variables:
      - $MANUAL_CLEANUP
  tags:
    - chef
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHA"
    when: always
    expire_in: 3 days
    paths:
      - artifacts/

.kitchen_test_definition: &kitchen_test_definition
  script:
    - kitchen converge $KITCHEN_NAME
    - kitchen verify $KITCHEN_NAME
  after_script:
    - export KITCHEN_YAML=kitchen.yml
    - export KITCHEN_LOCAL_YAML=kitchen.dokken.yml
    - kitchen destroy $KITCHEN_NAME
  retry: 1
  except:
    refs:
    - production
    variables:
      - $MANUAL_CLEANUP
  tags:
    - chef-kitchen
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    when: always
    expire_in: 3 days
    paths:
      - .kitchen/

kitchen_default-centos-7:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: default
  variables:
    KITCHEN_NAME: default-centos-7

kitchen_default-fedora-30:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: default
  variables:
    KITCHEN_NAME: default-fedora-30

kitchen_default-ubuntu-1910:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: default
  variables:
    KITCHEN_NAME: default-ubuntu-1910

kitchen_default-ubuntu-1804:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: default
  variables:
    KITCHEN_NAME: default-ubuntu-1804
    
kitchen_default-debian-8:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: default
  variables:
    KITCHEN_NAME: default-debian-8

kitchen_default-debian-9:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: default
  variables:
    KITCHEN_NAME: default-debian-9

kitchen_default-amazonlinux-2:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: default
  variables:
    KITCHEN_NAME: default-amazonlinux-2

kitchen_latest-centos-7:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: latest
  variables:
    KITCHEN_NAME: latest-centos-7

kitchen_latest-fedora-30:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: latest
  variables:
    KITCHEN_NAME: latest-fedora-30

kitchen_latest-ubuntu-1910:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: latest
  variables:
    KITCHEN_NAME: latest-ubuntu-1910

kitchen_latest-debian-9:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: latest
  variables:
    KITCHEN_NAME: latest-debian-9
kitchen_latest-debian-10:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: latest
  variables:
    KITCHEN_NAME: latest-debian-10

kitchen_latest-ubuntu-1804:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: latest
  variables:
    KITCHEN_NAME: latest-ubuntu-1804

kitchen_config-centos-7:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: config
  variables:
    KITCHEN_NAME: config-centos-7

kitchen_config-fedora-30:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: config
  variables:
    KITCHEN_NAME: config-fedora-30

kitchen_config-ubuntu-1910:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: config
  variables:
    KITCHEN_NAME: config-ubuntu-1910

kitchen_config-ubuntu-1804:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: config
  variables:
    KITCHEN_NAME: config-ubuntu-1804

kitchen_manual-centos-7:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: manual
  variables:
    KITCHEN_NAME: manual-centos-7

kitchen_manual-fedora-30:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: manual
  variables:
    KITCHEN_NAME: manual-fedora-30

kitchen_githead-centos-7:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: githead
  variables:
    KITCHEN_NAME: githead-centos-7

kitchen_githead-fedora-30:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: githead
  variables:
    KITCHEN_NAME: githead-fedora-30

kitchen_manual-ubuntu-1910:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: manual
  variables:
    KITCHEN_NAME: manual-ubuntu-1910

kitchen_manual-ubuntu-1804:
  <<: *kitchen_docker_template
  <<: *kitchen_test_definition
  stage: manual
  variables:
    KITCHEN_NAME: manual-ubuntu-1804

berks_upload:
  <<: *chef_docker_template
  stage: deploy
  script:
    - berks install
    - berks update
    - berks verify
    - berks upload --no-freeze --force --except integration
  environment:
    name: production
  only:
    - production
  except:
    variables:
      - $MANUAL_CLEANUP
  tags:
    - chef-berks-upload

cleanup_job:
  <<: *kitchen_docker_template
  stage: cleanup
  script:
    - kitchen destroy all
    - sudo rm -Rf /tmp/gitlab-runner-artifacts/*
  when: always
  except:
    refs:
    - production
    variables:
      - $MANUAL_CLEANUP
  tags:
    - chef-kitchen

manual_cleanup_job:
  <<: *kitchen_docker_template
  stage: cleanup_manual
  script:
    - kitchen destroy all
    - sudo rm -Rf /tmp/gitlab-runner-artifacts/*
  allow_failure: false
  when: manual
  only:
    variables:
      - $MANUAL_CLEANUP
  tags:
    - chef-kitchen
...
