---
driver:
  name: vagrant
  provider: hyperv
  network:
  - ["public_network", bridge: "Default Switch"]

platforms:
  - name: centos-7
  - name: fedora-29
    driver:
      box: generic/fedora29
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: debian-8
    driver:
      box: generic/debian8
  - name: debian-9
    driver:
      box: generic/debian9
  - name: amazonlinux-2
    driver_config:
      box: Yojimbo108/AmazonLinux2
...
