---
driver:
  name: vagrant
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: fedora-29
  - name: ubuntu-18.10
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-9.6

suites:
  - name: default
    run_list:           
      - recipe[syslog_ng_test]
    verifier:
      inspec_tests:
        - test/integration/default
...
