---
driver:
  name: vagrant
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-7
  - name: fedora-28

suites:
  - name: default
    run_list:           
      - recipe[syslog-ng]
    verifier:
      inspec_tests:
        - test/integration/default
...
