---
driver:
  name: dokken
  privileged: true
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

platforms:
- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd
    volumes:
      - /tmp/gitlab-runner-artifacts:/var/gitlab-runner-artifacts   
- name: fedora-28
  driver:
    image: dokken/fedora-28
    pid_one_command: /usr/lib/systemd/systemd
    volumes:
      - /tmp/gitlab-runner-artifacts:/var/gitlab-runner-artifacts
...
