---
driver:
  name: vagrant
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-7
  - name: fedora-29
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: debian-8
  - name: debian-9
  - name: amazonlinux-2
    driver_config:
      box: ywatase/amzn2

suites:
  - name: default
    run_list:   
      - recipe[syslog_ng_test::selinux]        
      - recipe[syslog_ng_test::package_distro]
      - recipe[syslog_ng_test::config_global]
    verifier:
      inspec_tests:
        - test/integration/default
  - name: latest
    excludes:
      - debian-8
      - debian-9
      - amazonlinux-2
    run_list:
      - recipe[syslog_ng_test::selinux]
      - recipe[syslog_ng_test::package_latest]
      - recipe[syslog_ng_test::config_global]
    verifier:
      inspec_tests:
        - test/integration/latest
  - name: config
    excludes:
      - debian-8
      - debian-9
      - amazonlinux-2
    run_list:
      - recipe[syslog_ng_test::selinux]
      - recipe[syslog_ng_test::cleanup]
      - recipe[syslog_ng_test::package_latest]
      - recipe[syslog_ng_test::config_global]
      - recipe[syslog_ng_test::destination]
      - recipe[syslog_ng_test::source]
      - recipe[syslog_ng_test::filter]
      - recipe[syslog_ng_test::log]
      - recipe[syslog_ng_test::template]
      - recipe[syslog_ng_test::parser]
      - recipe[syslog_ng_test::rewrite]
    verifier:
      inspec_tests:
        - test/integration/config
...
