# Use Travis's cointainer based infrastructure
sudo: false

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Run bundle install to add simplecov
install: chef exec bundle install

branches:
  only:
    - master

# Ensure we make ChefDK's Ruby the default
before_script:
  - eval "$(chef shell-init bash)"

stages:
  - test
  - kitchen


jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script:
        - chef --version
        - cookstyle --version
        - foodcritic --version
        - chef exec delivery local all
